books:
  - title: Pride and Prejudice
    author: Jane Austen
    year: 1813
  - title: To Kill A Mockingbird
    author: Harper Lee
    year: 1960
  - title: The Great Gatsby
    author: F. Scott Fitzgerald
    year: 1925