name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron:  '0 0 */1 * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        deno: ["v1.9.x", "nightly"]
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: ${{ matrix.deno }}

      - name: Cache Dependencies
        run: deno cache deps_test.ts

      - name: Run Tests
        run: deno test --allow-env --allow-read --allow-write --unstable
        